(Entorno Virtual) PS C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Backend> python manage.py runserver 
>>
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Anaconda\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception      
    raise _exception[1]
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
  File "C:\Anaconda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Backend\autenticacion\__init__.py", line 2, in <module>
    from django.contrib.auth.models import AbstractUser
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\contrib\auth\models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\contrib\auth\base_user.py", line 57, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\db\models\base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\apps\registry.py", line 260, in get_containing_app_config   
    self.check_apps_ready()
  File "C:\Users\jorge\OneDrive\Escritorio\Marketplace Supremo\Entorno Virtual\Lib\site-packages\django\apps\registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
